drop type dept_t force
drop type emp_t force


CREATE TYPE dept_t;
/

CREATE TYPE emp_t AS OBJECT(
 empno CHAR(6),
 firstname VARCHAR(12),
 lastname VARCHAR(15),
 workdept REF dept_t,
 sex CHAR(1),
 birthdate DATE,
 salary NUMBER(8,2)
);
/

CREATE TYPE dept_t AS OBJECT(
 deptno CHAR(3),
 deptname VARCHAR(36),
 mgrno REF emp_t,
 admrdept REF dept_t
);
/


CREATE TABLE OREMP of emp_t(
 empno PRIMARY KEY,
 firstname NOT NULL,
 lastname NOT NULL
);
/

CREATE TABLE ORDEPT of dept_t(
 deptno PRIMARY KEY,
 deptname NOT NULL
);
/


INSERT INTO oremp(empno, firstname, lastname, sex, birthdate, salary) values(
 '000010', 'CHRISTINE', 'HAAS', 'F', TO_DATE('1953-08-14', 'YYYY-MM-DD'), 72750
);
/

INSERT INTO oremp(empno, firstname, lastname, sex, birthdate, salary) values(
 '000020', 'MICHAEL', 'THOMPSON', 'M', TO_DATE('1968-02-02', 'YYYY-MM-DD'), 61250
);
/

INSERT INTO oremp(empno, firstname, lastname, sex, birthdate, salary) values(
 '000030', 'SALLY', 'KWAN', 'F', TO_DATE('1971-05-11','YYYY-MM-DD'), 58250
);
/
INSERT INTO oremp(empno, firstname, lastname, sex, birthdate,salary) 
VALUES ('000060', 'IRVING', 'STERN', 'M', TO_DATE('07/JUL/65', 'DD/MON/RR'), 55555);
INSERT INTO oremp(empno, firstname, lastname, sex, birthdate,salary) 
VALUES ('000070', 'EVA', 'PULASKI', 'F', TO_DATE('26/MAY/73 ', 'DD/MON/RR'), 56170);
INSERT INTO oremp(empno, firstname, lastname, sex, birthdate,salary) 
VALUES ('000050', 'JOHN', 'GEYER', 'M', TO_DATE('15/SEP/55', 'DD/MON/RR'), 60175);
INSERT INTO oremp(empno, firstname, lastname, sex, birthdate,salary) 
VALUES ('000090', 'EILEEN', 'HENDERSON', 'F', TO_DATE('15/MAY/61', 'DD/MON/RR'), 49750);
INSERT INTO oremp(empno, firstname, lastname, sex, birthdate,salary) 
VALUES ('000100', 'THEODORE', 'SPENSER', 'M', TO_DATE('18/DEC/76', 'DD/MON/RR'), 46150);


SELECT * FROM OREMP;
/



TRUNCATE TABLE ORDEPT;

INSERT INTO ORDEPT(DEPTNO, DEPTNAME, MGRNO) VALUES(
 'A00', 'SPIFFY COMPUTER SERVICE DIV.',(SELECT REF(E) FROM OREMP E WHERE E.EMPNO = '000010')
)

INSERT INTO ORDEPT(DEPTNO, DEPTNAME, MGRNO) VALUES(
 'B01', 'PLANNING', (SELECT REF(E) FROM OREMP E WHERE E.EMPNO='000020')
)

INSERT INTO ORDEPT(DEPTNO, DEPTNAME, MGRNO) VALUES(
 'C01', 'INFORMATION CENTRE', (SELECT REF(E) FROM OREMP E WHERE E.EMPNO='000030')
)

INSERT INTO ORDEPT(DEPTNO, DEPTNAME, MGRNO) VALUES(
 'D01', 'DEVELOPMENT CENTRE', (SELECT REF(E) FROM OREMP E WHERE E.EMPNO='000060')
)

SELECT * FROM ORDEPT



UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='A00')
WHERE EMPNO='000010';
/

SELECT * FROM OREMP;
/

UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='B01')
WHERE EMPNO='000020'

UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='C01')
WHERE EMPNO='000030';
/

UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='D01')
WHERE EMPNO='000060';
/

SELECT * FROM OREMP;


UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='D01')
WHERE EMPNO='000070';
/


UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='C01')
WHERE EMPNO='000050';
/
UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='B01')
WHERE EMPNO='000090';
/

UPDATE OREMP
SET WORKDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='B01')
WHERE EMPNO='000100';
/

SELECT * FROM OREMP;


SELECT E.EMPNO, E.WORKDEPT.DEPTNO 
FROM OREMP E;

SELECT * FROM ORDEPT;
/

UPDATE ORDEPT
SET ADMRDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='A00')
WHERE DEPTNO = 'A00';
/

UPDATE ORDEPT
SET ADMRDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='A00')
WHERE DEPTNO = 'B01';
/

UPDATE ORDEPT
SET ADMRDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='A00')
WHERE DEPTNO = 'C01';
/

UPDATE ORDEPT
SET ADMRDEPT = (SELECT REF(D) FROM ORDEPT D WHERE D.DEPTNO='C01')
WHERE DEPTNO = 'D01';
/


select * from ordept
select * from oremp

